### ISSUE TITLE
Slash in EPC QR Code's text parameter

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [heuer/segno#105]
Hi, I've noticed that I cannot include any slash character `'/'` in the `text=` parameter of the `helpers.make_epc_qr()` function, it won't appear on the QR code. What would do the trick? What can I do?

**Comment by heuer** [comment]
Thanks for your issue. I added a test case for the slash issue, see <https://github.com/heuer/segno/commit/8efb409648bfa6e7cb9c05a2e049f813525e257c>. It passes.
Can you provide an example which fails? 

TIA.

**Comment by heuer** [comment]
Closing this issue. Please reopen it if you continue to experience problems. 

Please enhance the test case <https://github.com/heuer/segno/blob/master/tests/test_issue_105_epc_slash.py>
