### ISSUE TITLE
TEL;TYPE=WORK

### ISSUE THREAD

**Issue by InLaw** [heuer/segno#108]
How to differentiate between e.g. TYPE=HOME and TYPE=WORK

ADR;`TYPE=HOME`:;;Heidestraße 17;Köln;;51147;Germany

https://de.wikipedia.org/wiki/VCard

**Comment by heuer** [comment]
TEL;TYPE=WORK should work with PR #106 

ADR;TYPE=HOME does not work, though.

**Comment by heuer** [comment]
Closing this issue. With release 1.5.2 TEL;TYPE=WORK is available.

I do not intend to implement ADR;TYPE=HOME, see also issue #107
