### ISSUE TITLE
Segno GUI and Windows prebuilt executables

### ISSUE THREAD

**Issue by deajan** [heuer/segno#117]
Hello,

I've built a GUI for segno at https://github.com/netinvent/segno_ui
The GUI is designed to work on Windows and Linux (both have been tested so far) and I provide prebuilt binaries for Windows in order to make segno as accessible as possible for new users.

Data fields are dynamically generated from helper function signatures, so if you add field, it will automatically be added to the GUI.

I'd love to get some feedback from you, and perhaps a link from your project to mine if you think it's good enough.

Best regards.

**Comment by heuer** [comment]
Thank you! 

I'll add a link to the docs and README.

**Comment by deajan** [comment]
Thank you for the effort you put into segno ;)

**Comment by deajan** [comment]
I think the mention of an optional UI and link to https://github.com/netinvent/segno_ui never was added to your actual README.
Recently updated the UI to be less clumsy.
