### ISSUE TITLE
Is it possible to round the edges

### ISSUE THREAD

**Issue by macmichael01** [heuer/segno#120]
Is it possible to round the edge of the data bits of the QR code like so:
<img width="112" alt="Screenshot 2023-05-20 at 1 40 18 AM" src="https://github.com/heuer/segno/assets/128222/2a8573cb-1b9b-4010-90b1-2dc568b352d5">

**Comment by heuer** [comment]
Sorry, that's not possible with this library. I have no intention of adding such a feature. This would have to be done by projects based on Segno, since such operations require additional libraries, such as Pillow. Segno should continue to be independent of other libraries.

**Comment by 5opr4ni** [comment]
Then no Segno, malissimo!
