### ISSUE TITLE
Add image while using .make_mecard module

### ISSUE THREAD

**Issue by Shadowsweep** [heuer/segno#131]
As i use .make_mecard the contact gets imported but not the image of the user

**Comment by heuer** [comment]
IMO MeCards don't provide images…

Please provide more information how you created the MeCard and what you expected.

**Comment by Shadowsweep** [comment]
Okk I tried it in vcard using photo_uri and it Gave error Data too large
DataOverflowError at /api/makeresume
Data too large. No QR Code can handle the provided data

def resume_qr(request):
    
    if request.method == 'POST':
        print("1")
        
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        background = request.FILES.get('image')
        url = request.POST.get('url')
        country = request.POST.get('country')
        city = request.POST.get('city')
        title = request.POST.get('title')
        color = request.POST.get('color')
        qrcode_v = helpers.make_vcard(
             name=name,
             photo_uri =  background,
             displayname=name,
             email= email,
             phone= phone,
             url=url,
             country=country,
             city=city,
             title=title
    
         )

![Screenshot 2023-11-30 200909](https://github.com/heuer/segno/assets/122604770/a2e274eb-982b-477e-9aa2-2411d9e14c75)

**Comment by heuer** [comment]
The problem are these lines here:
```background = request.FILES.get('image')```

```photo_uri =  background,```

You shouldn't use the image data but the image URL:

```python
qrcode_v = helpers.make_vcard(
         name=name,
         photo_uri =  'https://www.example.org/path/to/the/image'
         displayname=name,
         email= email,
         phone= phone,
         url=url,
         country=country,
         city=city,
         title=title
     )

```

**Comment by Shadowsweep** [comment]
okk Thanks 👍
