### ISSUE TITLE
Eyes and frames customize required!

### ISSUE THREAD

**Issue by aiddroid** [heuer/segno#136]
eyes and frames customize required!

**Comment by heuer** [comment]
Beyond the scope of this project as it would introduce dependencies on advanced graphic libs like Pillow. The lib should be self-contained and not have any dependencies on other libs.

**Comment by aiddroid** [comment]
> Beyond the scope of this project as it would introduce dependencies on advanced graphic libs like Pillow. The lib should be self-contained and not have any dependencies on other libs.

Can you add some callbacks or plugin APIs, that users can custom the style of the QR?

**Comment by heuer** [comment]
Segno supports usage of plugins, see https://segno.readthedocs.io/en/latest/plugins.html

https://github.com/heuer/qrcode-artistic/blob/master/qrcode_artistic.py may serve as an  example.
