### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bluetech** [heuer/segno#42]
This library is very well done:

- Has all features I could want.
- Nice API.
- Helpful CLI tool.
- Great docs & changelogs.
- No dependencies.
- Fast.
- Has tests.
- Permissive license.
- Can even render to the *terminal*!

It should be the default choice for QR handling in Python. Just wanted to say thanks for the hard work :)

**Comment by heuer** [comment]
Thanks for your kind words! :)
