### ISSUE TITLE
vcard field

### ISSUE THREAD

**Issue by pgdju** [heuer/segno#43]
Thank's for your work.

Is it possible to know all the different vcard fields we can introduce with segno? on segno.readthedocs.io, I only see the following parameters : 
qr = helpers.make_vcard(name='Doe;John', displayname='John Doe', email='me@example.org', phone='+1234567')

but there are many others parameters  : 
https://en.wikipedia.org/wiki/VCard#Properties

**Comment by heuer** [comment]
Thanks for your comment; only a subset of the vCard 3 standard is supported (supporting the complete specification isn't a goal of Segno). The support for vCard is more or less aligned to the meCard spec.

The documentation of the helpers module is located here: <https://segno.readthedocs.io/en/stable/api.html#module-segno.helpers>

If you have suggestions which fields should be supported, I'll consider to add the properties.

**Comment by heuer** [comment]
If you don't mind, I close the issue. If you've suggestions for additional properties, feel free to reopen it.
