### ISSUE TITLE
segno always append '0a' to the content

### ISSUE THREAD

**Issue by qman1989** [heuer/segno#49]
I use onlinebarcodereader to decode the qrcode that generate by segno and I find it always auto append '0a' to the content in hex values. How to remove it?

**Comment by heuer** [comment]
Thanks for your report.

Can you provide an example (or a test case)? 
Are you using the API or the command line script? 
Which decoder do you use?

Thanks.

**Comment by qman1989** [comment]
Thank you for your reply!

This is my code:
import sys
import segno
qr = segno.make('0H450116721300010000001-010010000000000011842118',  version=7, error='H')
qr.save('H.png', scale=5)

And I decode H.png by https://www.onlinebarcodereader.com/, the following image is the result.
![qr](https://user-images.githubusercontent.com/3711883/51301113-03d9bb80-1a69-11e9-9513-873502e01568.jpg)
The correct result should be:
![qr2](https://user-images.githubusercontent.com/3711883/51301175-38e60e00-1a69-11e9-970c-746e86e33093.jpg)

**Comment by heuer** [comment]
Thanks for your explanation. As I see it, the output (see "content" box) is correct (your screenshot does not show the complete box).

![result](https://user-images.githubusercontent.com/364926/51328449-b1ea6300-1a73-11e9-8cd3-6bdb06ad323a.png)

IMO it's a problem of the webservice and not a Segno issue. You can try QR codes generated by other libs (I used PyQRCode and libqrencode) and you'll always get the same result.

**Comment by qman1989** [comment]
Yes. It looks right, but in fact sengo append a "\n" to the content. We can find a '0a' in the end of the hex values and it's a "\n" ( hex(ord('\n')) = 0xa ).

**Comment by heuer** [comment]
> but in fact sengo append a "\n" to the content.

I guess the webservice adds it while decoding or presenting the hex code.

As written, the webservice always adds 0a regardless which QR code lib I tried.
Please try another QR code lib and you'll see that it adds the 0a to the result.

Here the result of another decoder (ZXing):

![zxingres](https://user-images.githubusercontent.com/364926/51370568-dd169600-1af7-11e9-88f6-52094cffec98.png)

**Comment by qman1989** [comment]
OK. I'll try it. Thank you very much.
