### ISSUE TITLE
Set error level and version

### ISSUE THREAD

**Issue by lopow** [heuer/segno#51]
I can not set error corr. Level to M if I ser version to 15. I need both values. How can I di this?

**Comment by heuer** [comment]
You can specify the error level via parameter ``error`` and the version via parameter ``version``. By default, segno tries to improve the error level. If you need a specific error level you can disable it via ``boost_error=False``.

Example:
```python
>>> import segno
>>> qr = segno.make('This is a test', error='m', version=15)
>>> qr.version
15
>>> qr.error
'H'
>>> # Segno changed the error level from M to H since there is enough space to improve the error level
>>> # Disable error boosting
>>> qr = segno.make('This is a test', error='m', version=15, boost_error=False)
>>> qr.version
15
>>> qr.error
'M'
```

**Comment by heuer** [comment]
PS: 
If ``boost_error`` is enabled (default), Segno tries to improve the error level **while keeping the specified version**. Segno never changes the version to get a better error correction level. 

If neither the version nor error correction level is specified, Segno creates a QR code with a minimal version (which fits for the given content), but maximal possible error correction level.

**Comment by lopow** [comment]
Hi, thanks a lot. You save my day. It is working. Thanks again
