### ISSUE TITLE
help! How to decode micro QR code

### ISSUE THREAD

**Issue by zjzyx** [heuer/segno#63]

**Comment by heuer** [comment]
Do you search for an app which can decode Micro QR Codes? I.e. <https://apps.apple.com/de/app/barcode-scanner-and-qr-reader/id601172795> is capable to decode Micro QR Codes.

**Comment by zjzyx** [comment]
Do you know the open source code of decode micro QR codes

**Comment by heuer** [comment]
No, sorry. There was a feature request for the Zxing lib to support Micro QR Code decoding but it was not fixed acc. to my knowledge

**Comment by edwardocano** [comment]
any update about how decode micro qr codes?

**Comment by edwardocano** [comment]
@heuer the app you mention can not decode micro qr.

**Comment by heuer** [comment]
@edwardocano, ensure that you've checked "Micro QR code" in the settings. 
It may be deactivated by default.
The app is capable to decode Micro QR codes

**Comment by edwardocano** [comment]
You are correct @heuer. thanks!

**Comment by ankitpriyarup** [comment]
Any new update regarding micro qr code decoding? I found these 2 repositories but couldn't make it work

https://github.com/tupunco/ZXing-CSharp
https://github.com/GordonCox/ZXing-CSharp-MicroQR-Detector/

**Comment by heuer** [comment]
> Any new update regarding micro qr code decoding? I found these 2 repositories but couldn't make it work

This lib is about encoding, not decoding, sorry.

**Comment by bessonmarc** [comment]
Hi, any new update regarding a micro qr code decoder in python? Micro QR codes are perfect for my project and I'm therefore very thankful for the opportunity that segno provides to encode them. However, the inability to decode them currently forces me to eventually work with classical qr codes, which are unnecessary larger (in size) and thus not ideal for my project.

**Comment by heuer** [comment]
> any new update regarding a micro qr code decoder in python?

Unfortunately, I am not aware of any decoders that are written in Python. Or libraries that could be used from Python.

A few Android and iOS apps can read Micro QR Codes, though.

**Comment by lessthanoptimal** [comment]
I've written a [Micro QR Code decoder / scanner / reader](https://boofcv.org/index.php?title=Example_Detect_Micro_QR_Code) and included it in [BoofCV](https://boofcv.org/). [PyBoof](https://pypi.org/project/PyBoof/) is the Python wrapper. [Example Code](https://github.com/lessthanoptimal/PyBoof/blob/v0.40.1/examples/microqr_detect.py).
