### ISSUE TITLE
Create similar "make_image" Method to offer support on django

### ISSUE THREAD

**Issue by DrJfrost** [heuer/segno#77]
I was trying to use this library to store a confirmation code on a django model wich has `ImageField` field type, since this library does not offer any clean way to get the image variable without storing it I could not use it.

similar libraries such as `qrcode` let you handle the image instance via the method `make_image` so that you can use it for any purpose, in this case saving it as part of a model field.

for example: 
```python
import qrcode

# Create qr code instance
qr = qrcode.QRCode(
    version = 1,
    error_correction = qrcode.constants.ERROR_CORRECT_H,
    box_size = 10,
    border = 4,
)

# The data that you want to store
data = "The Data that you need to store in the QR Code"

# Add data
qr.add_data(data)
qr.make(fit=True)

# Create an image from the QR Code instance
img = qr.make_image()

#From here I could make
model = Mymodel.objects.create(**fields)

img_name = "something.jpg"
buffer = BytesIO()
img.save(buffer, 'JPEG')
model.someimgfield.save(img_name, ContentFile(buffer.getvalue()), save=False)
model.save()
```
there is no purpose on optimizing the creation of the qr code If I am going to loose execution time writing the image on the server then loading it and then saving it again on the model/db.

please add this "Django" support that would attract many other people on using this, thanks =)

**Comment by heuer** [comment]
This may work:
```python
import io
import segno

# The data that you want to store
data = "The Data that you need to store in the QR Code"

# Create qr code instance
qr = segno.make(version=1, error='h')

img = io.ByteIO()
qr.save(img, kind='png', scale=10, border=4)

#From here I could make
model = Mymodel.objects.create(**fields)

img_name = "something.png"
model.someimgfield.save(img_name, ContentFile(buffer.getvalue()), save=False)
model.save()
```

Segno does not support JPEG and I think it makes no sense to use JPG as it is lossy while PNG offers smaller files and better quality. 

If you need to support of JPG, you can use the `pil` Plugin https://pypi.org/project/segno-pil/

```python
import io
import segno

# The data that you want to store
data = "The Data that you need to store in the QR Code"

# Create qr code instance
qr = segno.make(version=1, error='h')

img = qr.to_pil(scale=10, border=4)

#From here I could make
model = Mymodel.objects.create(**fields)

img_name = "something.jpg"
buffer = io.BytesIO()
img.save(buffer, 'JPEG')
model.someimgfield.save(img_name, ContentFile(buffer.getvalue()), save=False)
model.save()
```

**Comment by DrJfrost** [comment]
This example is just perfect I thought the save function did not support the `BytesIO` arg. I think you should add this use case to the documentation since you literally don't find anything about it on the internet :D

**Comment by heuer** [comment]
> . I think you should add this use case to the documentation

It's part of the docs:
<https://segno.readthedocs.io/en/stable/serializers.html#saving-qr-codes-to-streams>

;)

**Comment by DrJfrost** [comment]
Oh yeah sorry about that. what about pointing out some like "django" example in that section of the doc I think it's not very intuitive at this point.

**Comment by heuer** [comment]
Okay, I see. I'll add that.
