### ISSUE TITLE
Add Django example to the docs

### ISSUE THREAD

**Issue by heuer** [heuer/segno#78]
Enhance the docs and add an example how to save a QR Code in a Django model, see also #77 and <https://segno.readthedocs.io/en/stable/serializers.html#saving-qr-codes-to-streams>

**Comment by DrJfrost** [comment]
I just saw this issue was solved two days ago, I love the documentation it had, it was really detailed and even you created a section for "web development", I truly loved that!

**Comment by heuer** [comment]
Thanks for your kind words! :)
