### ISSUE TITLE
Can somebody explain message data codewords?

### ISSUE THREAD

**Issue by prnvjb** [heuer/segno#79]
Hi all,
Can somebody tell me how to get message data codewords for a given string from this library?
I'm working on message data codewords for my thesis as qrcode is not relevant to my project but my interest is on message data code words.
Please advise.
Many Thanks!!

**Comment by heuer** [comment]
Segno provides no public API to access the codewords. 

The public API focuses on the matrix.

You may have a look at ```encoder.py```. The [buffer](https://github.com/heuer/segno/blob/develop/segno/encoder.py#L227) contains the codewords but it is not accessible outside the ```_encode()``` function and there are no plans to make it accessible, sorry.

**Comment by prnvjb** [comment]
Thanks.
No Problem. I'll modify it accordingly.
