### ISSUE TITLE
CLI: Add support to change the encoding (i.e. UTF-8)

### ISSUE THREAD

**Issue by PaulKraut** [heuer/segno#84]
Hi,

Creating a qr-code with "German Umlauts":

`$ segno -o=fool.png --encoding="UTF-8" --title="Example QR code" "The Fool on [123-äöüÖÄÜ-456] the Hill"`

creates the fool.png file. Showing that png on my desktop and taking a picture smartphone (Galaxy Note 10), the smartphone finds the qr-code immediately, but it the German umlauts have been wrongly translated to some special characters (see Photo).

I use my Smartphone often to read qr-codes with Umlauts. I did not observe utf-8 decoding issues yet. Do you have any idea

Interestingly, fool.png can be decoded by zbarimg correctly as:
`$ zbarimg fool.png 
QR-Code:The Fool on [123-äöüÖÄÜ-456] the Hill`

Do you have any idea, why the qr-codes with German Umlauts are wrongly decoded by my smartphone, but correctly with zbarimg? Di you see any possibility for a workarounf or finxing? 

Thank you & kind regards,
![tempFileForShare_20200830-232619](https://user-images.githubusercontent.com/70487690/91670402-69cf6580-eb1d-11ea-813b-27689ce65a31.jpg)
![resized_fool](https://user-images.githubusercontent.com/70487690/91670406-6fc54680-eb1d-11ea-83bf-7e1836fca087.png)

**Comment by heuer** [comment]
Thanks for your report.

It seems to be a problem with the CLI. The QR code is not encoded with UTF-8 but ISO 8859-1.

The correct output (using UTF-8) would be:
![fool-utf-8](https://user-images.githubusercontent.com/364926/91696019-46cda180-eb6f-11ea-9358-8bb0142c8485.png)

```python
segno.make_qr('The Fool on [123-äöüÖÄÜ-456] the Hill', encoding='utf-8') \
     .save('fool-utf-8.png', scale=3)
```

ZXing and other decoders are able to decode both QR codes correctly, but I'll check why the command line interface ignores the encoding.

**Comment by heuer** [comment]
Ah, I got it! `--encoding` is used by the SVG serializer and is not used to encode the input. :(

I'm thinking of a solution, thanks for the hint!

**Comment by PaulKraut** [comment]
Hi,

thanks for the immediate response  :+1: 

Maybe it is worth to mention, that the encoding issue also exist when you use the helpers functions for any qr-code with free text:

I met the problem, when I tried to create a vcard qr-code with helpers.make_vcard() containing an Umlaut: I was not allowed to explicitly specify the encoding, yet.

Probably the best way would be, that the app detects itself, whether or not to fall back into UTF-8 encoding. But I have no clue, what this means for coding .. 

Kind regards,

**Comment by heuer** [comment]
> I met the problem, when I tried to create a vcard qr-code with helpers.make_vcard() containing an Umlaut: I was not allowed to explicitly specify the encoding, yet.

Well, I think the behaviour (try ISO 8859-1 and if it does not fit, use UTF-8) is correct acc. to ISO/IEC 18004. It seems to be an issue with the decoder app. Which decoder app do you use, btw? 

The `helpers` module provides for each QR code factory function also a `_data` function which can be used as input for `segno.make`.

```python
>>> import segno
>>> from segno import helpers
>>> qr = helpers.make_vcard(name='Müller;Änne', displayname='Änne Müller', email='aenne@example.org', phone='+1234567')
>>> qr.save('vcard-iso.png', scale=5)
>>> # Use the _data factory
>>> data = helpers.make_vcard_data(name='Müller;Änne', displayname='Änne Müller', email='aenne@example.org', phone='+1234567')
>>> # Create and save a QR code with an explicit encoding == UTF-8
>>> segno.make(data, encoding='utf-8').save('vcard-utf8.png', scale=5)
```

**Results**

**ISO 8859-1**
![vcard-iso](https://user-images.githubusercontent.com/364926/91717450-d1bf9380-eb91-11ea-97f1-79974a96d986.png)

Decoded (using ZXing)
![vcard-iso-decoded](https://user-images.githubusercontent.com/364926/91717451-d2582a00-eb91-11ea-9c68-04bde7451724.png)

**UTF-8**
![vcard-utf8](https://user-images.githubusercontent.com/364926/91717505-ef8cf880-eb91-11ea-9e35-e1e63e8482b9.png)

Decoded:
![vcard-utf8-decoded](https://user-images.githubusercontent.com/364926/91717506-f0258f00-eb91-11ea-889d-229a866bf997.png)

**Comment by PaulKraut** [comment]
> Well, I think the behaviour (try ISO 8859-1 and if it does not fit, use UTF-8) is correct acc. to ISO/IEC 18004. It seems to be an issue with the decoder app. Which decoder app do you use, btw?

Ah, now I got it, sorry:

In my first post, was confused why the zbarimg (linux, command line tool) returned the correct string, while the qr-decoder in the smartphone photo-app failed: zbarimg used latin-1 and the Samsung photo-App seems not to be able to handle latin-1.

> The `helpers` module provides for each QR code factory function also a `_data` function which can be used as input for `segno.make`.
> 
> ```python
> >>> import segno
> >>> from segno import helpers
> >>> qr = helpers.make_vcard(name='Müller;Änne', displayname='Änne Müller', email='aenne@example.org', phone='+1234567')
> >>> qr.save('vcard-iso.png', scale=5)
> >>> # Use the _data factory
> >>> data = helpers.make_vcard_data(name='Müller;Änne', displayname='Änne Müller', email='aenne@example.org', phone='+1234567')
> >>> # Create and save a QR code with an explicit encoding == UTF-8
> >>> segno.make(data, encoding='utf-8').save('vcard-utf8.png', scale=5)
> ```
> 
> **Results**
> 
> **ISO 8859-1**
> ![vcard-iso](https://user-images.githubusercontent.com/364926/91717450-d1bf9380-eb91-11ea-97f1-79974a96d986.png)
> 
> Decoded (using ZXing)
> ![vcard-iso-decoded](https://user-images.githubusercontent.com/364926/91717451-d2582a00-eb91-11ea-9c68-04bde7451724.png)
> 
> **UTF-8**
> ![vcard-utf8](https://user-images.githubusercontent.com/364926/91717505-ef8cf880-eb91-11ea-9e35-e1e63e8482b9.png)
> 
> Decoded:
> ![vcard-utf8-decoded](https://user-images.githubusercontent.com/364926/91717506-f0258f00-eb91-11ea-889d-229a866bf997.png)

Perfect! Helped a lot, thank you very much!

**Comment by heuer** [comment]
> Ah, now I got it, sorry:
> 
> In my first post, was confused why the zbarimg (linux, command line tool) returned the correct string, while the qr-decoder in the smartphone photo-app failed: zbarimg used latin-1 and the Samsung photo-App seems not to be able to handle latin-1.

No problem, thank you for discovering a bug! :+1: 

Your example

```
$ segno -o=fool.png --encoding="UTF-8" "The Fool on [123-äöüÖÄÜ-456] the Hill"
``` 

should work as expected with release 1.3.0
