### ISSUE TITLE
Anybody knows why this library do not let me create miniqr of this size? 

### ISSUE THREAD

**Issue by edwardocano** [heuer/segno#85]
![image](https://user-images.githubusercontent.com/30429170/92849362-db76a180-f3b0-11ea-907c-3f5c4a8d5275.png)
(I got this from this page https://barcode.tec-it.com/en/MicroQR?data=99999)
The smaller qr i can create is:

![99999L](https://user-images.githubusercontent.com/30429170/92849425-ecbfae00-f3b0-11ea-8499-f3f111fab4b9.png)

(I am not referring to the size of the image, i refer to the quantity of rows. )

**Comment by heuer** [comment]
Please provide more details. Segno creates M1 Micro QR codes if the input fits.

```python
>>> import segno 
>>> qr = segno.make(99999)  # Doesn't matter if the data is provided as int or str, btw
>>> qr.designator
'M1'
>>> qr.save('99999.png', scale=3)
```

Result:
![99999](https://user-images.githubusercontent.com/364926/92869874-8f088180-f403-11ea-9195-e36031cc7de9.png)

```python
>>> qr.save('99999.png', scale=24)
```

![99999](https://user-images.githubusercontent.com/364926/92870177-df7fdf00-f403-11ea-9702-422c3e6e6b5b.png)

**Comment by heuer** [comment]
The provided Micro QR code utilizes version M2. Data: 18848. I don't know why or how you created it, I get the following results:

```python
>>> import segno
>>> qr = segno.make('18848')
>>> qr.designator
'M1'
>>> qr.save('m1-18848.png', scale=6)
>>> qr = segno.make('18848', version='m2')
>>> qr.designator
'M2-M'
>>> qr.save('m2-18848.png', scale=6)
``` 

**M1**
![m1-18848](https://user-images.githubusercontent.com/364926/92876969-f8d85980-f40a-11ea-86ad-62a8f3925a47.png)


**M2**
![m2-18848](https://user-images.githubusercontent.com/364926/92876975-fd9d0d80-f40a-11ea-80c4-d537d637edd8.png)

**Comment by edwardocano** [comment]
Ok i understand. 

My code was. 
qr = segno.make_micro("99999",error = 'L',boost_error =False)

So the 'M1' has zero of correction level?

**Comment by heuer** [comment]
That's correct, M1 has no error correction. It can only take up to five numeric chars.

IMO it makes no sense to disable ``boost_error`` unless you encounter a performance problem. With ``boost_error=True`` (default) you'll get the best error correction level without changing the version / symbol size

**Comment by edwardocano** [comment]
Thanks for that info!
