### ISSUE TITLE
MacPorts Documentation

### ISSUE THREAD

**Issue by harens** [heuer/segno#87]
Following a discussion about the state of pyqrcode https://trac.macports.org/ticket/61342, both pyqrcodeng and segno were added to [MacPorts](https://www.macports.org)!

I thought it might be useful to document that their respective project pages can be found [here](https://ports.macports.org/port/py-segno/) and [here](https://ports.macports.org/port/py-pyqrcodeng/), and that they can both be installed on macOS by running the following:

```
sudo port install py-pyqrcodeng
sudo port install py-segno
```

I will try my best to update both of them with each new release, since I'm notified whenever you release a new version (although I understand that pyqrcodeng is no longer maintained). Let me know if you have any questions about this and thanks for the great software! 👍

**Comment by heuer** [comment]
Thanks for maintaining the port! :+1: 

I added a hint to the README
