### ISSUE TITLE
hanzi mode can't handle GB2312 properly

### ISSUE THREAD

**Issue by Rapiz1** [heuer/segno#89]
Thanks for your great work! This is the only python library I found with hanzi mode.
However, hanzi mode can't handle ASCII characters for now while GB2312 is actually ASCII compatible.
The problem is here in `encoder.py` https://github.com/heuer/segno/blob/9bf6f74237485d082d9251be8e0d0e463fd4ffea/segno/encoder.py#L1087-L1102

It only considers the Chinese characters and all ASCII characters will fall into the last branch, emitting invalid hanzi mode byte, even for \n and whitespace.

**Comment by Rapiz1** [comment]
I've figured out a quick fix and tested it in my case. See the pull request above.

**Comment by heuer** [comment]
Thanks for your report and fix. I'll take a look at it. 

The credit for the hanzi mode should go to @neycyanshi, though. 👍 

Can you provide a minimal test case like https://github.com/heuer/segno/blob/master/tests/test_hanzi.py
I.e. `test_issue_89.py` which allows the test runner to detect the problem and shows that your solution fixes it?
That would be great.

**Comment by Rapiz1** [comment]
Just for the record and people in need, hanzi mode is specified in GBT 18284-2000, a Chinese supplement standard for QR code, not an ISO one. And this mode uses GB2312 (a Chinese encoding standard) for encoding so it can handle ASCII characters and common Chinese characters.
This mode is not widely supported but it's very handy when processing large data, with an improvement of about 50% in terms of the capacity. However, WeChat supports it. So using this mode in China may not be an issue.

**Comment by neycyanshi** [comment]
> I've figured out a quick fix and tested it in my case. See the pull request above.

Although GB2312 is ASCII compatible, QR specification ISO/IEC 18004 and GBT 18284-2000 doesn't allow the use of ASCII inside Kanji/Hanzi segment. In 7.3.6 "Each two-byte character value is compacted to a 13-bit binary codeword".
You have to use byte mode if your input string for QR has ASCII.

**Comment by neycyanshi** [comment]
If your input string is "続きを読むabc*^?xyz" and you want to use Kanji mode for the Japanese characters, you have to separate the string into two segments.
`qr = segno.make(['続きを読む', 'abc*^?xyz'])`
The first segment will be detected as Kanji mode, and the second segment detected as Byte mode.
However, Hanzi mode cannot be auto detected. One reason is that Hanzi mode is not in ISO/IEC specification. Another reason is that some Japanese characters are the same as Chinese characters, and the segment may happens to be detected as Kanji mode instead of Hanzi mode.

**Comment by Rapiz1** [comment]
I just ran another test and it showed the reader can't read ASCII in GB2312. @neycyanshi You're right!

**Comment by heuer** [comment]
Thanks to you both, @Rapiz1 and @neycyanshi, for investigating and resolving the problem!

Thanks for the clarification regarding the hanzi mode, @neycyanshi!
