### ISSUE TITLE
Problem in making desing in qrcode

### ISSUE THREAD

**Issue by tazim404** [heuer/segno#92]
I want to as that how i can make qrcode with diffrent desings like this:
![image](https://user-images.githubusercontent.com/68907772/103300816-d011b980-4a25-11eb-98d3-b6c5735e4b05.png)
Eyes like this:
![image](https://user-images.githubusercontent.com/68907772/103300901-06e7cf80-4a26-11eb-877a-64ba24067e33.png)

and other beautiful desings...

**Comment by heuer** [comment]
I see, this was discussed in #86

Since it would introduce Pillow or PIL as dependency, I don't want to have this functionality in Segno but maybe in qrcode-artistic which depends on Pillow anyway, see also https://github.com/heuer/qrcode-artistic/issues/6
