### ISSUE TITLE
Desing

### ISSUE THREAD

**Issue by tazim404** [heuer/segno#93]
No one is telling to make beautiful  qrcode in a simple way just giving a link to go here and there .
Can anyone help please.

**Comment by heuer** [comment]
You cannot change the style of the patterns. 

It just isn't part of that library's job.

If you want do change the style, you've to do it by your own.

You can change the color of each module pattern, though. Just look into the docs: https://segno.readthedocs.io/en/latest/colorful-qrcodes.html
