### ISSUE TITLE
Password contains double quotation marks in helper.make_wifi_data result

### ISSUE THREAD

**Issue by dolphinwow** [heuer/segno#95]
Try to get the qrcode value by using helper.make_wifi_data.
However, among the generated qrcode result values, double quotation marks are included in the password.
Because of this, a password error occurs when scanning with a qrcode scanner.

I hope to check if there is a problem with my code.

My Code ====
qrVal = helpers.make_wifi_data(
                ssid=contentJson.get('ssid'),
                password=contentJson.get('password'),
                security=contentJson.get('security'),
                hidden=contentJson.get('hidden') == True)

Result ====
WIFI:T:WPA;S:"MySSID";P:"MyPassword";;

**Comment by heuer** [comment]
Thanks for your report. I cannot reproduce this, maybe the JSON data already contain quotation marks?

```python
>>> import segno.helpers
>>> segno.helpers.make_wifi_data(ssid='MySSID', password='MyPassword', security='wpa')
'WIFI:T:WPA;S:MySSID;P:MyPassword;;'
>>> segno.helpers.make_wifi_data(ssid='MySSID', password='MyPassword', security='wpa', hidden=True)
'WIFI:T:WPA;S:MySSID;P:MyPassword;H:true;'
```

**Comment by dolphinwow** [comment]
Hi, @heuer 
thank you for your reply.

In my case, I got different results as below.

------- my source code ------
if request.method == 'POST':
    content = request.data.get('content')

	contentJson = json.loads(content)
	qrVal = helpers.make_wifi_data(
	    ssid=contentJson.get('ssid'),
	    password=contentJson.get('password'),
	    security=contentJson.get('security'),
	    hidden=contentJson.get('hidden') == True)

------- success case -------
['content' value]
{"qrtype":"wifi","ssid":"myssid","password":"mypassward","security":"WPA","hidden":true}

['helpers.make_wifi_data' result]
WIFI:T:WPA;S:myssid;P:mypassward;H:true;

------- failed case -------
['content' value]
{"qrtype":"wifi","ssid":"myssid","password":"12341234","security":"WPA","hidden":true}

['helpers.make_wifi_data' result]
WIFI:T:WPA;S:myssid;P:"12341234";H:true;

**Comment by heuer** [comment]
Thanks for providing more insight into your code. Now I understand why the password is quoted. It should only happen if the password / SSID can be interpreted as an integer.
I'll fix it asap.

**Comment by dolphinwow** [comment]
@heuer Thank you for the quick answer. ^^
