### ISSUE TITLE
vCard v3 does not work on some fields (e.g. TEL / ADR)

### ISSUE THREAD

**Issue by curtis18** [heuer/segno#96]
Referring to the document https://segno.readthedocs.io/en/latest/contact-information.html,

vcard = helpers.make_vcard_data(name='Doe;John', displayname='John Doe', email='me@example.org', phone='+1234567') 

If the return is 
'BEGIN:VCARD\r\nVERSION:3.0\r\nN:Doe;John\r\nFN:John Doe\r\nEMAIL:me@example.org\r\nTEL:+1234567\r\nEND:VCARD\r\n'

vCard cannot be loaded properly since the string is missing property TYPE=WORK / TYPE=HOME
https://en.wikipedia.org/wiki/VCard#vCard_3.0
![image](https://user-images.githubusercontent.com/6743839/107600401-a66fc300-6c5e-11eb-829d-9a46c4107f5f.png)

I tried
vcard = helpers.make_vcard_data(name='Doe;John', displayname='John Doe', email='me@example.org', phone='+1234567') 
or 
vcard = helpers.make_vcard_data(name='Doe;John', displayname='John Doe', email='me@example.org', phone=('+1234567', '+1234567')) 
Tel numbers cannot be loaded after scanning the generated QR codes.

However, the example string on the wiki does not have the problem. Please help and thanks a lot.
![image](https://user-images.githubusercontent.com/6743839/107600854-ed11ed00-6c5f-11eb-8230-5a50d1e5e4d3.png)

**Comment by heuer** [comment]
Thanks for the hint.
Acc. to my knowledge the TYPE parameters are optional. At least vCard 4.0 states this explicitely. I'll take a look into the vCard 3 specifications and get back to you.

**Comment by heuer** [comment]
Acc. to https://tools.ietf.org/html/rfc2426#section-3.3.1 the "TYPE" parameter is optional. 
It states: 

TEL:
> The type can include the type parameter "TYPE" to specify intended use for the telephone number.
> [...]
> The default type is "voice".

ADR:
> The type can include the type parameter "TYPE" to specify the delivery address type.
> [...]
> The default is "TYPE=intl,postal,parcel,work".

I think the result is valid acc. to the vCard 3 specification. ZXing produces the same result, see https://zxing.appspot.com/generator

Are you just wondering about the missing TYPE parameter or is the QR code not recognized as a vCard?

**Comment by curtis18** [comment]
Thanks for your reply. The "TYPE" parameter should be optional. If there is an option to add TYPE parameter in the make_vcard_data method, it would be better since there are many Apps do not recognize the vCard without TYPE and adding TYPE options can provide more flexibility to identify the type of data (e.g. WORK / HOME TEL number). Currently, I am using make method to resolve the issue temporary.  qr = segno.make(vcard_string).

![image](https://user-images.githubusercontent.com/6743839/107896348-f73e2f00-6f70-11eb-9947-cc51ac18c65d.png)

e.g. QR Code Reader
![image](https://user-images.githubusercontent.com/6743839/107896579-a418ac00-6f71-11eb-928f-419b483a2c03.png)

![image](https://user-images.githubusercontent.com/6743839/107896637-cd393c80-6f71-11eb-9fce-5e2428166aaa.png)

**Comment by heuer** [comment]
Thanks for the explanation. The aim of the helpers.make_vcard() function is to offer a basic functionality for creating vCard QR codes.
The vCard standards are very complex and partly imprecise.
To cover the full vCard standard, I think it makes more sense to use something like vObject (https://pypi.org/project/vobject/), for example. 
The result can then be converted into a QR code via segno.make().

helpers.make_vcard() and helpers.make_vcard_data() are quite complex functions with (too) many parameters, so I would not like to add more params unless someone suggests a good API that doesn't further complicate the functions.

**Comment by annsellers2010-crypto** [comment]
https://quickshare.samsungcloud.com/t4mMPmuFxWNT
